# Generated by Django 4.1.3 on 2022-12-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookreview", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userfollows",
            constraint=models.CheckConstraint(
                check=models.Q(("user", models.F("followed_user")), _negated=True),
                name="not_same",
            ),
        ),
    ]
